In [1]:
import pandas as pd 
import numpy as np

In [2]:
df = pd.read_csv(r"D:\Ashish\Texas\Tarrant\Transaction_Log\Raw_Data\us_tx_48439_trxlog_data_legal_bronze_20260218.csv")
df

C:\Users\ashish.sharma\AppData\Local\Temp\ipykernel_45220\3463690471.py:1: DtypeWarning: Columns (0,8) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(r"D:\Ashish\Texas\Tarrant\Transaction_Log\Raw_Data\us_tx_48439_trxlog_data_legal_bronze_20260218.csv")

,instrument,legaltype,city,subdivision,block,low_lot,high_lot,remarks,book_page,page_save
0,D219293952,Subdivision,FORT WORTH,LIBERTY CROSSING,E,51,51,PLCAB A PLSLIDE 9415,NaN,D219293952.json
1,D220294163,Subdivision,FORT WORTH,OVERTON PARK,20,16,16,PLCAB 388-39 PLSLIDE 15,NaN,D220294163.json
2,D206206746,Subdivision,MNFLD,PLANTATION ESTS,1,1,1,PLCAB 388-182 PLSLIDE 7,NaN,D206206746.json
3,D206206714,Subdivision,NaN,SCOT WOODS ESTATES,2,17A,17A,NaN,NaN,D206206714.json
4,D220239232,Subdivision,NaN,ORIGINAL TOWN OF MANSFIELD,7,NaN,NaN,PLCAB 63 PLSLIDE 53,NaN,D220239232.json
...,...,...,...,...,...,...,...,...,...,...
2032746,NaN,Subdivision,GRPVNE,LAKE FOREST,NaN,38,38,PLCAB 388-25 PLSLIDE 95,14591_356,14591_356.json
2032747,NaN,Subdivision,FORT WORTH,HI MT,10,35,35,PLCAB 204-A PLSLIDE 151,16594_241,16594_241.json
2032748,D203438401,Subdivision,FT W,LEGACY SQ,5D,5,5,PLCAB A PLSLIDE 7476,NaN,D203438401.json
2032749,d218151945,Subdivision,HALTOM CITY,BRASWELL'S,1,4,4,PLCAB 1924 PLSLIDE 251,NaN,d218151945.json
2032750,D219186509,Subdivision,ARLINGTON,PARK HIGHLANDS,3,7,7,PLCAB A PLSLIDE 10547,NaN,D219186509.json

In [3]:
df[df['instrument'].isna()]

,instrument,legaltype,city,subdivision,block,low_lot,high_lot,remarks,book_page,page_save
1111707,NaN,Subdivision,NaN,LONDONDERRY,3,40,40,2084 444,8065_20,8065_20.json
1111708,NaN,Subdivision,NaN,PARKWOOD E,1,2,2,NaN,7686_1668,7686_1668.json
1111709,NaN,Subdivision,ARL,LAMAR N,1,4,4,PLCAB 388-88 PLSLIDE 55,15620_440,15620_440.json
1111710,NaN,Subdivision,NaN,LEE N,1,14,14,NaN,7871_1691,7871_1691.json
1111711,NaN,Subdivision,FORT WORTH,LAS BRISAS *,2,1,1,PLCAB 388-70 PLSLIDE 57,15502_17,15502_17.json
...,...,...,...,...,...,...,...,...,...,...
2032742,NaN,Subdivision,FORT WORTH,HIGHLAND PK,48,2,2,PLCAB 310 PLSLIDE 60,11520_1494,11520_1494.json
2032743,NaN,Subdivision,ARL,WESTWOOD,2,14,14,NaN,14100_558,14100_558.json
2032745,NaN,Subdivision,RICHLND HL,RICHLAND HILLS,H,2,2,PLCAB 388-K PLSLIDE 3,12590_1954,12590_1954.json
2032746,NaN,Subdivision,GRPVNE,LAKE FOREST,NaN,38,38,PLCAB 388-25 PLSLIDE 95,14591_356,14591_356.json
2032747,NaN,Subdivision,FORT WORTH,HI MT,10,35,35,PLCAB 204-A PLSLIDE 151,16594_241,16594_241.json

In [4]:
df[df['instrument']=='D185506331']

Empty DataFrame
Columns: [instrument, legaltype, city, subdivision, block, low_lot, high_lot, remarks, book_page, page_save]
Index: []

In [5]:
df[df['instrument']=='D200246656']

Empty DataFrame
Columns: [instrument, legaltype, city, subdivision, block, low_lot, high_lot, remarks, book_page, page_save]
Index: []

In [6]:
df[df['book_page'].isna()]

,instrument,legaltype,city,subdivision,block,low_lot,high_lot,remarks,book_page,page_save
0,D219293952,Subdivision,FORT WORTH,LIBERTY CROSSING,E,51,51,PLCAB A PLSLIDE 9415,NaN,D219293952.json
1,D220294163,Subdivision,FORT WORTH,OVERTON PARK,20,16,16,PLCAB 388-39 PLSLIDE 15,NaN,D220294163.json
2,D206206746,Subdivision,MNFLD,PLANTATION ESTS,1,1,1,PLCAB 388-182 PLSLIDE 7,NaN,D206206746.json
3,D206206714,Subdivision,NaN,SCOT WOODS ESTATES,2,17A,17A,NaN,NaN,D206206714.json
4,D220239232,Subdivision,NaN,ORIGINAL TOWN OF MANSFIELD,7,NaN,NaN,PLCAB 63 PLSLIDE 53,NaN,D220239232.json
...,...,...,...,...,...,...,...,...,...,...
2032741,D208001263,Subdivision,FT W,HERITAGE GLEN,1,26,26,PLCAB A PLSLIDE 7118,NaN,D208001263.json
2032744,D224056510,Subdivision,FORT WORTH,EDERVILLE PARK TOWNHOMES,A,1R-51,1R-51,PLCAB A PLSLIDE 12078,NaN,D224056510.json
2032748,D203438401,Subdivision,FT W,LEGACY SQ,5D,5,5,PLCAB A PLSLIDE 7476,NaN,D203438401.json
2032749,d218151945,Subdivision,HALTOM CITY,BRASWELL'S,1,4,4,PLCAB 1924 PLSLIDE 251,NaN,d218151945.json
2032750,D219186509,Subdivision,ARLINGTON,PARK HIGHLANDS,3,7,7,PLCAB A PLSLIDE 10547,NaN,D219186509.json

## Case-1 Found any column side null equivalnat so replace with null

In [7]:
 # Define fake null values
fake_nulls = ['', 'null', 'none', 'nan', "None", 'na', 'n/a', 'n.a.', 'NaN', 'NAN', 'NULL', 'nil', 'Nan', 'Null',"NONE"]

# ✅ Now check and replace in all columns
for col in df.columns:
    mask = df[col].astype(str).str.lower().isin([str(x).lower() for x in fake_nulls])
    problem_rows = df.loc[mask, [col]]

    if not problem_rows.empty:
        print(f"Rows where '{col}' has fake nulls:")
        print(problem_rows)

        df[col] = df[col].replace(fake_nulls, np.nan)
print("\nNaN count per column:")

print(df.isna().sum())
print("\nCleaned DataFrame:")
print(df)

Rows where 'instrument' has fake nulls:
        instrument
1111707        NaN
1111708        NaN
1111709        NaN
1111710        NaN
1111711        NaN
...            ...
2032742        NaN
2032743        NaN
2032745        NaN
2032746        NaN
2032747        NaN

[876576 rows x 1 columns]
Rows where 'city' has fake nulls:
         city
3         NaN
4         NaN
15        NaN
19        NaN
64        NaN
...       ...
2032722  NONE
2032729   NaN
2032733   NaN
2032734   NaN
2032740  NONE

[230108 rows x 1 columns]
Rows where 'subdivision' has fake nulls:
        subdivision
1058            NaN
1187            NaN
1452            NaN
2220            NaN
2419            NaN
...             ...
2012681         NaN
2014276         NaN
2023064         NaN
2031223         NaN
2031463         NaN

[2254 rows x 1 columns]
Rows where 'block' has fake nulls:
        block
121       NaN
122       NaN
134       NaN
268       NaN
320       NaN
...       ...
2032706   NaN
2032707   NaN
2032722   NaN
2032733   NaN
2032746   NaN

[138598 rows x 1 columns]
Rows where 'low_lot' has fake nulls:
        low_lot
4           NaN
134         NaN
268         NaN
462         NaN
676         NaN
...         ...
2032671     NaN
2032706     NaN
2032707     NaN
2032722     NaN
2032733     NaN

[83954 rows x 1 columns]
Rows where 'high_lot' has fake nulls:
        high_lot
4            NaN
134          NaN
268          NaN
462          NaN
676          NaN
...          ...
2032671      NaN
2032706      NaN
2032707      NaN
2032722      NaN
2032733      NaN

[83954 rows x 1 columns]
Rows where 'remarks' has fake nulls:
        remarks
3           NaN
58          NaN
123         NaN
146         NaN
151         NaN
...         ...
2032723     NaN
2032725     NaN
2032729     NaN
2032733     NaN
2032743     NaN

[341792 rows x 1 columns]
Rows where 'book_page' has fake nulls:
        book_page
0             NaN
1             NaN
2             NaN
3             NaN
4             NaN
...           ...
2032741       NaN
2032744       NaN
2032748       NaN
2032749       NaN
2032750       NaN

[1156175 rows x 1 columns]

NaN count per column:
instrument      876576
legaltype            0
city            230108
subdivision       2254
block           138598
low_lot          83954
high_lot         83954
remarks         341792
book_page      1156175
page_save            0
dtype: int64

Cleaned DataFrame:
         instrument    legaltype         city                 subdivision  \
0        D219293952  Subdivision   FORT WORTH            LIBERTY CROSSING
1        D220294163  Subdivision   FORT WORTH                OVERTON PARK
2        D206206746  Subdivision        MNFLD             PLANTATION ESTS
3        D206206714  Subdivision          NaN          SCOT WOODS ESTATES
4        D220239232  Subdivision          NaN  ORIGINAL TOWN OF MANSFIELD
...             ...          ...          ...                         ...
2032746         NaN  Subdivision       GRPVNE                 LAKE FOREST
2032747         NaN  Subdivision   FORT WORTH                       HI MT
2032748  D203438401  Subdivision         FT W                   LEGACY SQ
2032749  d218151945  Subdivision  HALTOM CITY                  BRASWELL'S
2032750  D219186509  Subdivision    ARLINGTON              PARK HIGHLANDS

        block low_lot high_lot                  remarks  book_page  \
0           E      51       51     PLCAB A PLSLIDE 9415        NaN
1          20      16       16  PLCAB 388-39 PLSLIDE 15        NaN
2           1       1        1  PLCAB 388-182 PLSLIDE 7        NaN
3           2     17A      17A                      NaN        NaN
4           7     NaN      NaN      PLCAB 63 PLSLIDE 53        NaN
...       ...     ...      ...                      ...        ...
2032746   NaN      38       38  PLCAB 388-25 PLSLIDE 95  14591_356
2032747    10      35       35  PLCAB 204-A PLSLIDE 151  16594_241
2032748    5D       5        5     PLCAB A PLSLIDE 7476        NaN
2032749     1       4        4   PLCAB 1924 PLSLIDE 251        NaN
2032750     3       7        7    PLCAB A PLSLIDE 10547        NaN

               page_save
0        D219293952.json
1        D220294163.json
2        D206206746.json
3        D206206714.json
4        D220239232.json
...                  ...
2032746   14591_356.json
2032747   16594_241.json
2032748  D203438401.json
2032749  d218151945.json
2032750  D219186509.json

[2032751 rows x 10 columns]

## Case-2 Removing the extra spaces

In [8]:
import re
for col in df.select_dtypes(include=['object']).columns:
    df[col] = df[col].apply(
        lambda x: re.sub(r'\s+', ' ', x).strip() if isinstance(x, str) else x
    )


## Checked below column

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2032751 entries, 0 to 2032750
Data columns (total 10 columns):
 #   Column       Dtype
---  ------       -----
 0   instrument   object
 1   legaltype    object
 2   city         object
 3   subdivision  object
 4   block        object
 5   low_lot      object
 6   high_lot     object
 7   remarks      object
 8   book_page    object
 9   page_save    object
dtypes: object(10)
memory usage: 155.1+ MB

In [10]:
df['legaltype'].value_counts()

legaltype
Subdivision    2032751
Name: count, dtype: int64

In [11]:
df['city'].value_counts()

city
FORT WORTH                411184
FT W                      377307
ARL                       266868
ARLINGTON                  60649
HURST                      35599
                           ...
WESTOVER HILLS VILLAGE         1
BUL                            1
388-90                         1
MEADOWS                        1
FOERT                          1
Name: count, Length: 948, dtype: int64

In [12]:
# Work on string view for consistency
df_str = df.astype(str)

problem_columns_by_type = {}

# --- find single-character string values ---
single_char_values = (
    df_str
    .where(df.notna())
    .apply(lambda c: c[c.str.len() == 1])
    .stack()
    .unique()
)

# --- values to check (include 0 and 0.0) ---
values_to_check = set(single_char_values) | {"0", "0.0"}

# --- run checks ---
for val in sorted(values_to_check):
    result = (df_str == val).sum()
    result = result[result > 0]

    if result.empty:
        continue

    # Print per-value output
    print(f"\n=== Single-character / zero values ({val}) ===")
    print(result.to_string())

    # Store problem-wise column list
    problem_columns_by_type[f"Value ({val})"] = result.index.tolist()

# --- final summary ---
print("\n=== Problem-wise column lists ===")
for k, v in problem_columns_by_type.items():
    print(f"{k}: {v}")

=== Single-character / zero values (!) ===
block       1
low_lot     1
high_lot    1

=== Single-character / zero values (&) ===
block       3
low_lot     1
high_lot    1
remarks     1

=== Single-character / zero values (*) ===
city            1
low_lot         4
high_lot        4
remarks     15699

=== Single-character / zero values (+) ===
block    1

=== Single-character / zero values (,) ===
block    1

=== Single-character / zero values (-) ===
city       1
remarks    1

=== Single-character / zero values (.) ===
block       1
low_lot     9
high_lot    9
remarks     1

=== Single-character / zero values (/) ===
low_lot     3
high_lot    3

=== Single-character / zero values (0) ===
city          3
block       139
low_lot      42
high_lot     42
remarks       1

=== Single-character / zero values (1) ===
city            14
block       213577
low_lot      96349
high_lot     96349

=== Single-character / zero values (2) ===
city            13
block       164751
low_lot      85238
high_lot     85238

=== Single-character / zero values (3) ===
city            11
block       130567
low_lot      84204
high_lot     84204

=== Single-character / zero values (4) ===
city            32
block       111619
low_lot      81338
high_lot     81338

=== Single-character / zero values (5) ===
city           21
block       91606
low_lot     79743
high_lot    79743

=== Single-character / zero values (6) ===
city           70
block       77440
low_lot     77269
high_lot    77269

=== Single-character / zero values (7) ===
city           13
block       67898
low_lot     76150
high_lot    76150

=== Single-character / zero values (8) ===
city           15
block       60146
low_lot     72754
high_lot    72754
remarks         2

=== Single-character / zero values (9) ===
city            2
block       51851
low_lot     70087
high_lot    70087
remarks         2

=== Single-character / zero values (A) ===
city           11
block       43400
low_lot      3822
high_lot     3822

=== Single-character / zero values (B) ===
subdivision        2
block          29860
low_lot         2914
high_lot        2914

=== Single-character / zero values (C) ===
subdivision        1
block          23566
low_lot         2245
high_lot        2245

=== Single-character / zero values (D) ===
subdivision        1
block          19422
low_lot         1707
high_lot        1707

=== Single-character / zero values (E) ===
city            4
block       15552
low_lot      1306
high_lot     1306

=== Single-character / zero values (F) ===
city            5
block       11871
low_lot      1030
high_lot     1030

=== Single-character / zero values (G) ===
block       10378
low_lot       917
high_lot      917

=== Single-character / zero values (H) ===
city           1
block       8150
low_lot      703
high_lot     703

=== Single-character / zero values (I) ===
city           1
block       4494
low_lot      297
high_lot     297

=== Single-character / zero values (J) ===
subdivision       1
block          7204
low_lot         548
high_lot        548

=== Single-character / zero values (K) ===
city           3
block       5890
low_lot      459
high_lot     459

=== Single-character / zero values (L) ===
city              4
subdivision       1
block          6039
low_lot         393
high_lot        393

=== Single-character / zero values (M) ===
city           1
block       3246
low_lot      311
high_lot     311

=== Single-character / zero values (N) ===
city              3
subdivision       1
block          3065
low_lot         319
high_lot        319

=== Single-character / zero values (O) ===
block       2296
low_lot      208
high_lot     208

=== Single-character / zero values (P) ===
city           2
block       2746
low_lot      227
high_lot     227

=== Single-character / zero values (Q) ===
city           1
block       1962
low_lot      164
high_lot     164

=== Single-character / zero values (R) ===
city           2
block       2311
low_lot      191
high_lot     191

=== Single-character / zero values (S) ===
city              3
subdivision       3
block          2060
low_lot         165
high_lot        165

=== Single-character / zero values (T) ===
block       2002
low_lot      111
high_lot     111

=== Single-character / zero values (U) ===
city           2
block       1257
low_lot      122
high_lot     122

=== Single-character / zero values (V) ===
block       1178
low_lot       89
high_lot      89

=== Single-character / zero values (W) ===
block       1018
low_lot       73
high_lot      73

=== Single-character / zero values (X) ===
city           1
block       1027
low_lot       79
high_lot      79

=== Single-character / zero values (Y) ===
block       664
low_lot      72
high_lot     72

=== Single-character / zero values (Z) ===
block       720
low_lot      56
high_lot     56

=== Single-character / zero values (\) ===
city        1
low_lot     3
high_lot    3

=== Single-character / zero values (]) ===
low_lot     1
high_lot    1

=== Single-character / zero values (`) ===
city        5
block       7
low_lot     1
high_lot    1
remarks     6

=== Problem-wise column lists ===
Value (!): ['block', 'low_lot', 'high_lot']
Value (&): ['block', 'low_lot', 'high_lot', 'remarks']
Value (*): ['city', 'low_lot', 'high_lot', 'remarks']
Value (+): ['block']
Value (,): ['block']
Value (-): ['city', 'remarks']
Value (.): ['block', 'low_lot', 'high_lot', 'remarks']
Value (/): ['low_lot', 'high_lot']
Value (0): ['city', 'block', 'low_lot', 'high_lot', 'remarks']
Value (1): ['city', 'block', 'low_lot', 'high_lot']
Value (2): ['city', 'block', 'low_lot', 'high_lot']
Value (3): ['city', 'block', 'low_lot', 'high_lot']
Value (4): ['city', 'block', 'low_lot', 'high_lot']
Value (5): ['city', 'block', 'low_lot', 'high_lot']
Value (6): ['city', 'block', 'low_lot', 'high_lot']
Value (7): ['city', 'block', 'low_lot', 'high_lot']
Value (8): ['city', 'block', 'low_lot', 'high_lot', 'remarks']
Value (9): ['city', 'block', 'low_lot', 'high_lot', 'remarks']
Value (A): ['city', 'block', 'low_lot', 'high_lot']
Value (B): ['subdivision', 'block', 'low_lot', 'high_lot']
Value (C): ['subdivision', 'block', 'low_lot', 'high_lot']
Value (D): ['subdivision', 'block', 'low_lot', 'high_lot']
Value (E): ['city', 'block', 'low_lot', 'high_lot']
Value (F): ['city', 'block', 'low_lot', 'high_lot']
Value (G): ['block', 'low_lot', 'high_lot']
Value (H): ['city', 'block', 'low_lot', 'high_lot']
Value (I): ['city', 'block', 'low_lot', 'high_lot']
Value (J): ['subdivision', 'block', 'low_lot', 'high_lot']
Value (K): ['city', 'block', 'low_lot', 'high_lot']
Value (L): ['city', 'subdivision', 'block', 'low_lot', 'high_lot']
Value (M): ['city', 'block', 'low_lot', 'high_lot']
Value (N): ['city', 'subdivision', 'block', 'low_lot', 'high_lot']
Value (O): ['block', 'low_lot', 'high_lot']
Value (P): ['city', 'block', 'low_lot', 'high_lot']
Value (Q): ['city', 'block', 'low_lot', 'high_lot']
Value (R): ['city', 'block', 'low_lot', 'high_lot']
Value (S): ['city', 'subdivision', 'block', 'low_lot', 'high_lot']
Value (T): ['block', 'low_lot', 'high_lot']
Value (U): ['city', 'block', 'low_lot', 'high_lot']
Value (V): ['block', 'low_lot', 'high_lot']
Value (W): ['block', 'low_lot', 'high_lot']
Value (X): ['city', 'block', 'low_lot', 'high_lot']
Value (Y): ['block', 'low_lot', 'high_lot']
Value (Z): ['block', 'low_lot', 'high_lot']
Value (\): ['city', 'low_lot', 'high_lot']
Value (]): ['low_lot', 'high_lot']
Value (`): ['city', 'block', 'low_lot', 'high_lot', 'remarks']

In [13]:
df[col] = df[col].replace(['!',''])

C:\Users\ashish.sharma\AppData\Local\Temp\ipykernel_45220\1282555087.py:1: FutureWarning: Series.replace without 'value' and with non-dict-like 'to_replace' is deprecated and will raise in a future version. Explicitly specify the new values instead.
  df[col] = df[col].replace(['!',''])

In [14]:
df[df['city'].str.len()==1]

,instrument,legaltype,city,subdivision,block,low_lot,high_lot,remarks,book_page,page_save
137149,D222097832,Subdivision,8,CHASEWOOD CONDOMINIUM,A,101,101,PLCAB 34,NaN,D222097832.json
240672,D203421432,Subdivision,6,PARK GLEN,117,3,3,PLCAB A PLSLIDE 2138,NaN,D203421432.json
479010,D220327707,Subdivision,A,STONE GATE,1,38,38,PLCAB 184,NaN,D220327707.json
659720,D221025961,Subdivision,E,R B ENGLISH AND FRANCIS A ENGLISH 480 ACRE SURVEY,NaN,NaN,NaN,PLCAB 3091 PLSLIDE 242,NaN,D221025961.json
739172,D221362882,Subdivision,2,MARINA DEL RAY TOWNHOUSES,B,22,22,PLCAB 24,NaN,D221362882.json
...,...,...,...,...,...,...,...,...,...,...
2009098,NaN,Subdivision,6,BELMONT,7,5R1,5R1,NaN,11026_1746,11026_1746.json
2012100,NaN,Subdivision,6,SYLVAN HTS,8,12,12,PLCAB 1019 PLSLIDE 376,11081_1366,11081_1366.json
2015925,NaN,Subdivision,Q,OAKS OF BDFRD,4,32,32,PLCAB A PLSLIDE 1703,14150_230,14150_230.json
2016123,NaN,Subdivision,6,MEADOW CRK,38,2,2,PLCAB 388-176 PLSLIDE 48,15918_413,15918_413.json
2017804,NaN,Subdivision,3,J R MURPHY,NaN,M,M,PLCAB 388-9 PLSLIDE 353,10951_1244,10951_1244.json

In [15]:
df[df["block"].astype(str).str.contains("0", na=False)]

,instrument,legaltype,city,subdivision,block,low_lot,high_lot,remarks,book_page,page_save
1,D220294163,Subdivision,FORT WORTH,OVERTON PARK,20,16,16,PLCAB 388-39 PLSLIDE 15,NaN,D220294163.json
14,D219216795,Subdivision,WATAUGA,QUAIL MEADOWS ESTATES,10,6,6,PLCAB 388-198 PLSLIDE 17,NaN,D219216795.json
19,D218165835,Subdivision,NaN,CARSON RANCH ESTATES,20,7,7,PLCAB A PLSLIDE 7114,NaN,D218165835.json
28,D219075535,Subdivision,WATAUGA,QUAIL MEADOW ESTATES,10,3,3,PLCAB 388-198 PLSLIDE 17,NaN,D219075535.json
52,D225007460,Subdivision,NORTH RICHLAND HILLS,FOX HOLLOW,20R,15,15,PLCAB 388-177 PLSLIDE 61,NaN,D225007460.json
...,...,...,...,...,...,...,...,...,...,...
2032711,D212008844,Subdivision,S PK,ROBERTSON HUNTER,10,15R,15R,PLCAB A PLSLIDE 3436,NaN,D212008844.json
2032714,NaN,Subdivision,NaN,SOUTH WAYSIDE,10,10,10,NaN,8330_1011,8330_1011.json
2032738,NaN,Subdivision,FORT WORTH,CANDLERIDGE,610,10,10,PLCAB A PLSLIDE 6455,15474_228,15474_228.json
2032739,NaN,Subdivision,FORT WORTH,RIDGLEA W,20,7,7,PLCAB 388-C PLSLIDE 79,16526_214,16526_214.json
2032747,NaN,Subdivision,FORT WORTH,HI MT,10,35,35,PLCAB 204-A PLSLIDE 151,16594_241,16594_241.json

In [16]:
df[df['block']=='0']

,instrument,legaltype,city,subdivision,block,low_lot,high_lot,remarks,book_page,page_save
20213,D218209099,Subdivision,GRAND PRAIRIE,OAK HOLLOW,0,9,9,PLCAB 388-160 PLSLIDE 60,NaN,D218209099.json
20216,D221197592,Subdivision,GRAND PRAIRIE,OAK HOLLOW,0,9,9,PLCAB 388-160 PLSLIDE 60,NaN,D221197592.json
30081,D216078987,Subdivision,G P,MIRA LAGOS #B,0,9,9,PLCAB A PLSLIDE 9309,NaN,D216078987.json
44830,D211128644,Subdivision,NaN,LIVE OAK CRK,0,9,9,PLCAB A PLSLIDE 12888,NaN,D211128644.json
47323,D204071784,Subdivision,NaN,COVENTRY,0,20,20,NaN,NaN,D204071784.json
...,...,...,...,...,...,...,...,...,...,...
1921526,D211124936,Subdivision,N R H,NORTH RICHLD HILLS TWN CENT,0,29,29,PLCAB A PLSLIDE 6464,NaN,D211124936.json
1997708,NaN,Subdivision,ARL,SOUTH HAMPTON,0,20,20,PLCAB A PLSLIDE 6849,15776_169,15776_169.json
2000924,NaN,Subdivision,NaN,606 NORTH PARKRIDGE,0,0,0,NaN,13968_379,13968_379.json
2008368,NaN,Subdivision,HURST,HAVEN,0,12,12,NaN,8876_1244,8876_1244.json
2019960,NaN,Subdivision,NaN,CINNAMON RIDGE,0,8,8,2126 436+,8202_2124,8202_2124.json

In [17]:
replace_map = {
    "!": ['block', 'low_lot', 'high_lot'],
    "&": ['block', 'low_lot', 'high_lot', 'remarks'],
    "*": ['city', 'low_lot', 'high_lot', 'remarks'],
    "+": ['block'],
    ",": ['block'],
    "-": ['city', 'remarks'],
    ".": ['block', 'low_lot', 'high_lot', 'remarks'],
    "/": ['low_lot', 'high_lot'],
    "0": ['city', 'block', 'low_lot', 'high_lot', 'remarks'],
    "\\": ['city', 'low_lot', 'high_lot'],
    "]": ['low_lot', 'high_lot'],
    "`": ['city', 'block', 'low_lot', 'high_lot', 'remarks'],
    
}

for char, cols in replace_map.items():
    for col in cols:
        if col in df.columns:
            df[col] = df[col].replace(char,np.nan)

In [18]:
df[df["block"].astype(str).str.contains("0", na=False)]

,instrument,legaltype,city,subdivision,block,low_lot,high_lot,remarks,book_page,page_save
1,D220294163,Subdivision,FORT WORTH,OVERTON PARK,20,16,16,PLCAB 388-39 PLSLIDE 15,NaN,D220294163.json
14,D219216795,Subdivision,WATAUGA,QUAIL MEADOWS ESTATES,10,6,6,PLCAB 388-198 PLSLIDE 17,NaN,D219216795.json
19,D218165835,Subdivision,NaN,CARSON RANCH ESTATES,20,7,7,PLCAB A PLSLIDE 7114,NaN,D218165835.json
28,D219075535,Subdivision,WATAUGA,QUAIL MEADOW ESTATES,10,3,3,PLCAB 388-198 PLSLIDE 17,NaN,D219075535.json
52,D225007460,Subdivision,NORTH RICHLAND HILLS,FOX HOLLOW,20R,15,15,PLCAB 388-177 PLSLIDE 61,NaN,D225007460.json
...,...,...,...,...,...,...,...,...,...,...
2032711,D212008844,Subdivision,S PK,ROBERTSON HUNTER,10,15R,15R,PLCAB A PLSLIDE 3436,NaN,D212008844.json
2032714,NaN,Subdivision,NaN,SOUTH WAYSIDE,10,10,10,NaN,8330_1011,8330_1011.json
2032738,NaN,Subdivision,FORT WORTH,CANDLERIDGE,610,10,10,PLCAB A PLSLIDE 6455,15474_228,15474_228.json
2032739,NaN,Subdivision,FORT WORTH,RIDGLEA W,20,7,7,PLCAB 388-C PLSLIDE 79,16526_214,16526_214.json
2032747,NaN,Subdivision,FORT WORTH,HI MT,10,35,35,PLCAB 204-A PLSLIDE 151,16594_241,16594_241.json

In [21]:
106008 - 139

105869

In [19]:
df[df['block']=='0']

Empty DataFrame
Columns: [instrument, legaltype, city, subdivision, block, low_lot, high_lot, remarks, book_page, page_save]
Index: []

In [20]:
# Work on string view for consistency
df_str = df.astype(str)

problem_columns_by_type = {}

# --- find single-character string values ---
single_char_values = (
    df_str
    .where(df.notna())
    .apply(lambda c: c[c.str.len() == 1])
    .stack()
    .unique()
)

# --- values to check (include 0 and 0.0) ---
values_to_check = set(single_char_values) | {"0", "0.0"}

# --- run checks ---
for val in sorted(values_to_check):
    result = (df_str == val).sum()
    result = result[result > 0]

    if result.empty:
        continue

    # Print per-value output
    print(f"\n=== Single-character / zero values ({val}) ===")
    print(result.to_string())

    # Store problem-wise column list
    problem_columns_by_type[f"Value ({val})"] = result.index.tolist()

# --- final summary ---
print("\n=== Problem-wise column lists ===")
for k, v in problem_columns_by_type.items():
    print(f"{k}: {v}")

=== Single-character / zero values (1) ===
city            14
block       213577
low_lot      96349
high_lot     96349

=== Single-character / zero values (2) ===
city            13
block       164751
low_lot      85238
high_lot     85238

=== Single-character / zero values (3) ===
city            11
block       130567
low_lot      84204
high_lot     84204

=== Single-character / zero values (4) ===
city            32
block       111619
low_lot      81338
high_lot     81338

=== Single-character / zero values (5) ===
city           21
block       91606
low_lot     79743
high_lot    79743

=== Single-character / zero values (6) ===
city           70
block       77440
low_lot     77269
high_lot    77269

=== Single-character / zero values (7) ===
city           13
block       67898
low_lot     76150
high_lot    76150

=== Single-character / zero values (8) ===
city           15
block       60146
low_lot     72754
high_lot    72754
remarks         2

=== Single-character / zero values (9) ===
city            2
block       51851
low_lot     70087
high_lot    70087
remarks         2

=== Single-character / zero values (A) ===
city           11
block       43400
low_lot      3822
high_lot     3822

=== Single-character / zero values (B) ===
subdivision        2
block          29860
low_lot         2914
high_lot        2914

=== Single-character / zero values (C) ===
subdivision        1
block          23566
low_lot         2245
high_lot        2245

=== Single-character / zero values (D) ===
subdivision        1
block          19422
low_lot         1707
high_lot        1707

=== Single-character / zero values (E) ===
city            4
block       15552
low_lot      1306
high_lot     1306

=== Single-character / zero values (F) ===
city            5
block       11871
low_lot      1030
high_lot     1030

=== Single-character / zero values (G) ===
block       10378
low_lot       917
high_lot      917

=== Single-character / zero values (H) ===
city           1
block       8150
low_lot      703
high_lot     703

=== Single-character / zero values (I) ===
city           1
block       4494
low_lot      297
high_lot     297

=== Single-character / zero values (J) ===
subdivision       1
block          7204
low_lot         548
high_lot        548

=== Single-character / zero values (K) ===
city           3
block       5890
low_lot      459
high_lot     459

=== Single-character / zero values (L) ===
city              4
subdivision       1
block          6039
low_lot         393
high_lot        393

=== Single-character / zero values (M) ===
city           1
block       3246
low_lot      311
high_lot     311

=== Single-character / zero values (N) ===
city              3
subdivision       1
block          3065
low_lot         319
high_lot        319

=== Single-character / zero values (O) ===
block       2296
low_lot      208
high_lot     208

=== Single-character / zero values (P) ===
city           2
block       2746
low_lot      227
high_lot     227

=== Single-character / zero values (Q) ===
city           1
block       1962
low_lot      164
high_lot     164

=== Single-character / zero values (R) ===
city           2
block       2311
low_lot      191
high_lot     191

=== Single-character / zero values (S) ===
city              3
subdivision       3
block          2060
low_lot         165
high_lot        165

=== Single-character / zero values (T) ===
block       2002
low_lot      111
high_lot     111

=== Single-character / zero values (U) ===
city           2
block       1257
low_lot      122
high_lot     122

=== Single-character / zero values (V) ===
block       1178
low_lot       89
high_lot      89

=== Single-character / zero values (W) ===
block       1018
low_lot       73
high_lot      73

=== Single-character / zero values (X) ===
city           1
block       1027
low_lot       79
high_lot      79

=== Single-character / zero values (Y) ===
block       664
low_lot      72
high_lot     72

=== Single-character / zero values (Z) ===
block       720
low_lot      56
high_lot     56

=== Problem-wise column lists ===
Value (1): ['city', 'block', 'low_lot', 'high_lot']
Value (2): ['city', 'block', 'low_lot', 'high_lot']
Value (3): ['city', 'block', 'low_lot', 'high_lot']
Value (4): ['city', 'block', 'low_lot', 'high_lot']
Value (5): ['city', 'block', 'low_lot', 'high_lot']
Value (6): ['city', 'block', 'low_lot', 'high_lot']
Value (7): ['city', 'block', 'low_lot', 'high_lot']
Value (8): ['city', 'block', 'low_lot', 'high_lot', 'remarks']
Value (9): ['city', 'block', 'low_lot', 'high_lot', 'remarks']
Value (A): ['city', 'block', 'low_lot', 'high_lot']
Value (B): ['subdivision', 'block', 'low_lot', 'high_lot']
Value (C): ['subdivision', 'block', 'low_lot', 'high_lot']
Value (D): ['subdivision', 'block', 'low_lot', 'high_lot']
Value (E): ['city', 'block', 'low_lot', 'high_lot']
Value (F): ['city', 'block', 'low_lot', 'high_lot']
Value (G): ['block', 'low_lot', 'high_lot']
Value (H): ['city', 'block', 'low_lot', 'high_lot']
Value (I): ['city', 'block', 'low_lot', 'high_lot']
Value (J): ['subdivision', 'block', 'low_lot', 'high_lot']
Value (K): ['city', 'block', 'low_lot', 'high_lot']
Value (L): ['city', 'subdivision', 'block', 'low_lot', 'high_lot']
Value (M): ['city', 'block', 'low_lot', 'high_lot']
Value (N): ['city', 'subdivision', 'block', 'low_lot', 'high_lot']
Value (O): ['block', 'low_lot', 'high_lot']
Value (P): ['city', 'block', 'low_lot', 'high_lot']
Value (Q): ['city', 'block', 'low_lot', 'high_lot']
Value (R): ['city', 'block', 'low_lot', 'high_lot']
Value (S): ['city', 'subdivision', 'block', 'low_lot', 'high_lot']
Value (T): ['block', 'low_lot', 'high_lot']
Value (U): ['city', 'block', 'low_lot', 'high_lot']
Value (V): ['block', 'low_lot', 'high_lot']
Value (W): ['block', 'low_lot', 'high_lot']
Value (X): ['city', 'block', 'low_lot', 'high_lot']
Value (Y): ['block', 'low_lot', 'high_lot']
Value (Z): ['block', 'low_lot', 'high_lot']

In [22]:
df["city"] = df["city"].mask(
    df["city"].astype(str).str.strip().str.len() == 1
)

In [23]:
# Work on string view for consistency
df_str = df.astype(str)

problem_columns_by_type = {}

# --- find single-character string values ---
single_char_values = (
    df_str
    .where(df.notna())
    .apply(lambda c: c[c.str.len() == 1])
    .stack()
    .unique()
)

# --- values to check (include 0 and 0.0) ---
values_to_check = set(single_char_values) | {"0", "0.0"}

# --- run checks ---
for val in sorted(values_to_check):
    result = (df_str == val).sum()
    result = result[result > 0]

    if result.empty:
        continue

    # Print per-value output
    print(f"\n=== Single-character / zero values ({val}) ===")
    print(result.to_string())

    # Store problem-wise column list
    problem_columns_by_type[f"Value ({val})"] = result.index.tolist()

# --- final summary ---
print("\n=== Problem-wise column lists ===")
for k, v in problem_columns_by_type.items():
    print(f"{k}: {v}")

=== Single-character / zero values (1) ===
block       213577
low_lot      96349
high_lot     96349

=== Single-character / zero values (2) ===
block       164751
low_lot      85238
high_lot     85238

=== Single-character / zero values (3) ===
block       130567
low_lot      84204
high_lot     84204

=== Single-character / zero values (4) ===
block       111619
low_lot      81338
high_lot     81338

=== Single-character / zero values (5) ===
block       91606
low_lot     79743
high_lot    79743

=== Single-character / zero values (6) ===
block       77440
low_lot     77269
high_lot    77269

=== Single-character / zero values (7) ===
block       67898
low_lot     76150
high_lot    76150

=== Single-character / zero values (8) ===
block       60146
low_lot     72754
high_lot    72754
remarks         2

=== Single-character / zero values (9) ===
block       51851
low_lot     70087
high_lot    70087
remarks         2

=== Single-character / zero values (A) ===
block       43400
low_lot      3822
high_lot     3822

=== Single-character / zero values (B) ===
subdivision        2
block          29860
low_lot         2914
high_lot        2914

=== Single-character / zero values (C) ===
subdivision        1
block          23566
low_lot         2245
high_lot        2245

=== Single-character / zero values (D) ===
subdivision        1
block          19422
low_lot         1707
high_lot        1707

=== Single-character / zero values (E) ===
block       15552
low_lot      1306
high_lot     1306

=== Single-character / zero values (F) ===
block       11871
low_lot      1030
high_lot     1030

=== Single-character / zero values (G) ===
block       10378
low_lot       917
high_lot      917

=== Single-character / zero values (H) ===
block       8150
low_lot      703
high_lot     703

=== Single-character / zero values (I) ===
block       4494
low_lot      297
high_lot     297

=== Single-character / zero values (J) ===
subdivision       1
block          7204
low_lot         548
high_lot        548

=== Single-character / zero values (K) ===
block       5890
low_lot      459
high_lot     459

=== Single-character / zero values (L) ===
subdivision       1
block          6039
low_lot         393
high_lot        393

=== Single-character / zero values (M) ===
block       3246
low_lot      311
high_lot     311

=== Single-character / zero values (N) ===
subdivision       1
block          3065
low_lot         319
high_lot        319

=== Single-character / zero values (O) ===
block       2296
low_lot      208
high_lot     208

=== Single-character / zero values (P) ===
block       2746
low_lot      227
high_lot     227

=== Single-character / zero values (Q) ===
block       1962
low_lot      164
high_lot     164

=== Single-character / zero values (R) ===
block       2311
low_lot      191
high_lot     191

=== Single-character / zero values (S) ===
subdivision       3
block          2060
low_lot         165
high_lot        165

=== Single-character / zero values (T) ===
block       2002
low_lot      111
high_lot     111

=== Single-character / zero values (U) ===
block       1257
low_lot      122
high_lot     122

=== Single-character / zero values (V) ===
block       1178
low_lot       89
high_lot      89

=== Single-character / zero values (W) ===
block       1018
low_lot       73
high_lot      73

=== Single-character / zero values (X) ===
block       1027
low_lot       79
high_lot      79

=== Single-character / zero values (Y) ===
block       664
low_lot      72
high_lot     72

=== Single-character / zero values (Z) ===
block       720
low_lot      56
high_lot     56

=== Problem-wise column lists ===
Value (1): ['block', 'low_lot', 'high_lot']
Value (2): ['block', 'low_lot', 'high_lot']
Value (3): ['block', 'low_lot', 'high_lot']
Value (4): ['block', 'low_lot', 'high_lot']
Value (5): ['block', 'low_lot', 'high_lot']
Value (6): ['block', 'low_lot', 'high_lot']
Value (7): ['block', 'low_lot', 'high_lot']
Value (8): ['block', 'low_lot', 'high_lot', 'remarks']
Value (9): ['block', 'low_lot', 'high_lot', 'remarks']
Value (A): ['block', 'low_lot', 'high_lot']
Value (B): ['subdivision', 'block', 'low_lot', 'high_lot']
Value (C): ['subdivision', 'block', 'low_lot', 'high_lot']
Value (D): ['subdivision', 'block', 'low_lot', 'high_lot']
Value (E): ['block', 'low_lot', 'high_lot']
Value (F): ['block', 'low_lot', 'high_lot']
Value (G): ['block', 'low_lot', 'high_lot']
Value (H): ['block', 'low_lot', 'high_lot']
Value (I): ['block', 'low_lot', 'high_lot']
Value (J): ['subdivision', 'block', 'low_lot', 'high_lot']
Value (K): ['block', 'low_lot', 'high_lot']
Value (L): ['subdivision', 'block', 'low_lot', 'high_lot']
Value (M): ['block', 'low_lot', 'high_lot']
Value (N): ['subdivision', 'block', 'low_lot', 'high_lot']
Value (O): ['block', 'low_lot', 'high_lot']
Value (P): ['block', 'low_lot', 'high_lot']
Value (Q): ['block', 'low_lot', 'high_lot']
Value (R): ['block', 'low_lot', 'high_lot']
Value (S): ['subdivision', 'block', 'low_lot', 'high_lot']
Value (T): ['block', 'low_lot', 'high_lot']
Value (U): ['block', 'low_lot', 'high_lot']
Value (V): ['block', 'low_lot', 'high_lot']
Value (W): ['block', 'low_lot', 'high_lot']
Value (X): ['block', 'low_lot', 'high_lot']
Value (Y): ['block', 'low_lot', 'high_lot']
Value (Z): ['block', 'low_lot', 'high_lot']

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2032751 entries, 0 to 2032750
Data columns (total 10 columns):
 #   Column       Dtype
---  ------       -----
 0   instrument   object
 1   legaltype    object
 2   city         object
 3   subdivision  object
 4   block        object
 5   low_lot      object
 6   high_lot     object
 7   remarks      object
 8   book_page    object
 9   page_save    object
dtypes: object(10)
memory usage: 155.1+ MB

In [25]:
df

,instrument,legaltype,city,subdivision,block,low_lot,high_lot,remarks,book_page,page_save
0,D219293952,Subdivision,FORT WORTH,LIBERTY CROSSING,E,51,51,PLCAB A PLSLIDE 9415,NaN,D219293952.json
1,D220294163,Subdivision,FORT WORTH,OVERTON PARK,20,16,16,PLCAB 388-39 PLSLIDE 15,NaN,D220294163.json
2,D206206746,Subdivision,MNFLD,PLANTATION ESTS,1,1,1,PLCAB 388-182 PLSLIDE 7,NaN,D206206746.json
3,D206206714,Subdivision,NaN,SCOT WOODS ESTATES,2,17A,17A,NaN,NaN,D206206714.json
4,D220239232,Subdivision,NaN,ORIGINAL TOWN OF MANSFIELD,7,NaN,NaN,PLCAB 63 PLSLIDE 53,NaN,D220239232.json
...,...,...,...,...,...,...,...,...,...,...
2032746,NaN,Subdivision,GRPVNE,LAKE FOREST,NaN,38,38,PLCAB 388-25 PLSLIDE 95,14591_356,14591_356.json
2032747,NaN,Subdivision,FORT WORTH,HI MT,10,35,35,PLCAB 204-A PLSLIDE 151,16594_241,16594_241.json
2032748,D203438401,Subdivision,FT W,LEGACY SQ,5D,5,5,PLCAB A PLSLIDE 7476,NaN,D203438401.json
2032749,d218151945,Subdivision,HALTOM CITY,BRASWELL'S,1,4,4,PLCAB 1924 PLSLIDE 251,NaN,d218151945.json
2032750,D219186509,Subdivision,ARLINGTON,PARK HIGHLANDS,3,7,7,PLCAB A PLSLIDE 10547,NaN,D219186509.json

In [26]:
df.duplicated().sum()

np.int64(1)

In [27]:
df = df.drop_duplicates(keep='first')

In [28]:
df.duplicated().sum()

np.int64(0)

In [29]:
# Define fake null values
fake_nulls = ['', 'null', 'none', 'nan', "None", 'na', 'n/a', 'n.a.', 'NaN', 'NAN', 'NULL', 'nil', 'Nan', 'Null',"NONE"]

# ✅ Now check and replace in all columns
for col in df.columns:
    mask = df[col].astype(str).str.lower().isin([str(x).lower() for x in fake_nulls])
    problem_rows = df.loc[mask, [col]]

    if not problem_rows.empty:
        print(f"Rows where '{col}' has fake nulls:")
        print(problem_rows)

        df[col] = df[col].replace(fake_nulls, np.nan)
print("\nNaN count per column:")

print(df.isna().sum())
print("\nCleaned DataFrame:")
print(df)

Rows where 'instrument' has fake nulls:
        instrument
1111707        NaN
1111708        NaN
1111709        NaN
1111710        NaN
1111711        NaN
...            ...
2032742        NaN
2032743        NaN
2032745        NaN
2032746        NaN
2032747        NaN

[876575 rows x 1 columns]

C:\Users\ashish.sharma\AppData\Local\Temp\ipykernel_45220\3716141602.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = df[col].replace(fake_nulls, np.nan)

Rows where 'city' has fake nulls:
        city
3        NaN
4        NaN
15       NaN
19       NaN
64       NaN
...      ...
2032722  NaN
2032729  NaN
2032733  NaN
2032734  NaN
2032740  NaN

[230353 rows x 1 columns]

C:\Users\ashish.sharma\AppData\Local\Temp\ipykernel_45220\3716141602.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = df[col].replace(fake_nulls, np.nan)

Rows where 'subdivision' has fake nulls:
        subdivision
1058            NaN
1187            NaN
1452            NaN
2220            NaN
2419            NaN
...             ...
2012681         NaN
2014276         NaN
2023064         NaN
2031223         NaN
2031463         NaN

[2254 rows x 1 columns]

C:\Users\ashish.sharma\AppData\Local\Temp\ipykernel_45220\3716141602.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = df[col].replace(fake_nulls, np.nan)

Rows where 'block' has fake nulls:
        block
121       NaN
122       NaN
134       NaN
268       NaN
320       NaN
...       ...
2032706   NaN
2032707   NaN
2032722   NaN
2032733   NaN
2032746   NaN

[138751 rows x 1 columns]

C:\Users\ashish.sharma\AppData\Local\Temp\ipykernel_45220\3716141602.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = df[col].replace(fake_nulls, np.nan)

Rows where 'low_lot' has fake nulls:
        low_lot
4           NaN
134         NaN
268         NaN
462         NaN
676         NaN
...         ...
2032671     NaN
2032706     NaN
2032707     NaN
2032722     NaN
2032733     NaN

[84019 rows x 1 columns]

C:\Users\ashish.sharma\AppData\Local\Temp\ipykernel_45220\3716141602.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = df[col].replace(fake_nulls, np.nan)

Rows where 'high_lot' has fake nulls:
        high_lot
4            NaN
134          NaN
268          NaN
462          NaN
676          NaN
...          ...
2032671      NaN
2032706      NaN
2032707      NaN
2032722      NaN
2032733      NaN

[84019 rows x 1 columns]

C:\Users\ashish.sharma\AppData\Local\Temp\ipykernel_45220\3716141602.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = df[col].replace(fake_nulls, np.nan)

Rows where 'remarks' has fake nulls:
        remarks
3           NaN
58          NaN
123         NaN
146         NaN
151         NaN
...         ...
2032723     NaN
2032725     NaN
2032729     NaN
2032733     NaN
2032743     NaN

[357501 rows x 1 columns]

C:\Users\ashish.sharma\AppData\Local\Temp\ipykernel_45220\3716141602.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = df[col].replace(fake_nulls, np.nan)

Rows where 'book_page' has fake nulls:
        book_page
0             NaN
1             NaN
2             NaN
3             NaN
4             NaN
...           ...
2032741       NaN
2032744       NaN
2032748       NaN
2032749       NaN
2032750       NaN

[1156175 rows x 1 columns]

C:\Users\ashish.sharma\AppData\Local\Temp\ipykernel_45220\3716141602.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = df[col].replace(fake_nulls, np.nan)

NaN count per column:
instrument      876575
legaltype            0
city            230353
subdivision       2254
block           138751
low_lot          84019
high_lot         84019
remarks         357501
book_page      1156175
page_save            0
dtype: int64

Cleaned DataFrame:
         instrument    legaltype         city                 subdivision  \
0        D219293952  Subdivision   FORT WORTH            LIBERTY CROSSING
1        D220294163  Subdivision   FORT WORTH                OVERTON PARK
2        D206206746  Subdivision        MNFLD             PLANTATION ESTS
3        D206206714  Subdivision          NaN          SCOT WOODS ESTATES
4        D220239232  Subdivision          NaN  ORIGINAL TOWN OF MANSFIELD
...             ...          ...          ...                         ...
2032746         NaN  Subdivision       GRPVNE                 LAKE FOREST
2032747         NaN  Subdivision   FORT WORTH                       HI MT
2032748  D203438401  Subdivision         FT W                   LEGACY SQ
2032749  d218151945  Subdivision  HALTOM CITY                  BRASWELL'S
2032750  D219186509  Subdivision    ARLINGTON              PARK HIGHLANDS

        block low_lot high_lot                  remarks  book_page  \
0           E      51       51     PLCAB A PLSLIDE 9415        NaN
1          20      16       16  PLCAB 388-39 PLSLIDE 15        NaN
2           1       1        1  PLCAB 388-182 PLSLIDE 7        NaN
3           2     17A      17A                      NaN        NaN
4           7     NaN      NaN      PLCAB 63 PLSLIDE 53        NaN
...       ...     ...      ...                      ...        ...
2032746   NaN      38       38  PLCAB 388-25 PLSLIDE 95  14591_356
2032747    10      35       35  PLCAB 204-A PLSLIDE 151  16594_241
2032748    5D       5        5     PLCAB A PLSLIDE 7476        NaN
2032749     1       4        4   PLCAB 1924 PLSLIDE 251        NaN
2032750     3       7        7    PLCAB A PLSLIDE 10547        NaN

               page_save
0        D219293952.json
1        D220294163.json
2        D206206746.json
3        D206206714.json
4        D220239232.json
...                  ...
2032746   14591_356.json
2032747   16594_241.json
2032748  D203438401.json
2032749  d218151945.json
2032750  D219186509.json

[2032750 rows x 10 columns]

In [30]:
import re
for col in df.select_dtypes(include=['object']).columns:
    df[col] = df[col].apply(
        lambda x: re.sub(r'\s+', ' ', x).strip() if isinstance(x, str) else x
    )

C:\Users\ashish.sharma\AppData\Local\Temp\ipykernel_45220\807524606.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = df[col].apply(

## Placing the file

In [31]:
df.to_csv(r"D:\Ashish\Texas\Tarrant\Transaction_Log\Cleaned_Data\us_tx_48439_data_trxlog_legal_silver_20260218.csv",index=False)