In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv(r"D:\Khushi\Cleansing_Data\us\texas\tarrant\transaction_log\Raw_Data\us_tx_48439_data_prop_sales_bronze_20260218.csv",dtype={'acc_nu':str})
df

C:\Users\khushi.limbachiya\AppData\Local\Temp\ipykernel_12932\1581676924.py:1: DtypeWarning: Columns (3,4) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(r"D:\Khushi\Cleansing_Data\us\texas\tarrant\transaction_log\Raw_Data\us_tx_48439_data_prop_sales_bronze_20260218.csv",dtype={'acc_nu':str})

,acc_nu,geo_no,instrument,deed_volume,deed_page,date,owner_name,page_save
0,02097354,31280-20-8,D221362700,NaN,NaN,12/10/2021,ESTES JOHN DAVID;ESTES STACY LABORDE,02097354.html
1,02097354,31280-20-8,D218282153,NaN,NaN,12/28/2018,CROCKETT AMY;CROCKETT EMILY,02097354.html
2,02097354,31280-20-8,D214122114,0000000,0.0,6/6/2014,RAMSAY THOMAS W,02097354.html
3,02097354,31280-20-8,00116860000180,0011686,180.0,8/5/1994,BEAN CHERYL;BEAN JOHN III,02097354.html
4,02097354,31280-20-8,00116860000134,0011686,134.0,7/11/1994,MIDLAND LAND INVESTMENTS INC,02097354.html
...,...,...,...,...,...,...,...,...
3014858,07254253,26368C-1-49,00141080000603,14108.0,603.0,11/12/1999,HOUCK E DWAIN;HOUCK K DAWN,07254253.html
3014859,07254253,26368C-1-49,00000000000000,0.0,0.0,1/1/1998,D R HORTON TEXAS LTD,07254253.html
3014860,40228584,33901C-4-26,D203318382,17118.0,372.0,8/22/2003,SHISLER KERRY,40228584.html
3014861,40228584,33901C-4-26,00167460000006,16746.0,6.0,5/22/2003,GOODMAN FAMILY OF BLDRS LP,40228584.html
3014862,40228584,33901C-4-26,00000000000000,0.0,0.0,1/1/2003,IPCF,40228584.html

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3014863 entries, 0 to 3014862
Data columns (total 8 columns):
 #   Column       Dtype
---  ------       -----
 0   acc_nu       object
 1   geo_no       object
 2   instrument   object
 3   deed_volume  object
 4   deed_page    object
 5   date         object
 6   owner_name   object
 7   page_save    object
dtypes: object(8)
memory usage: 184.0+ MB

In [4]:
# Define fake null values
fake_nulls = ['', 'null', 'none', 'nan', "None", 'na', 'n/a', 'n.a.', 'NaN', 'NAN', 'NULL', 'nil', 'Nan', 'Null','NONE']

# ✅ Now check and replace in all columns
for col in df.columns:
    mask = df[col].astype(str).str.lower().isin([str(x).lower() for x in fake_nulls])
    problem_rows = df.loc[mask, [col]]

    if not problem_rows.empty:
        print(f"Rows where '{col}' has fake nulls:")
        print(problem_rows)

        df[col] = df[col].replace(fake_nulls, np.nan)
print("\nNaN count per column:")

print(df.isna().sum())
print("\nCleaned DataFrame:")
print(df)

Rows where 'instrument' has fake nulls:
        instrument
1412           NaN
7756           NaN
35863          NaN
50167          NaN
83847          NaN
...            ...
2975568        NaN
2988031        NaN
2992264        NaN
3009586        NaN
3011815        NaN

[290 rows x 1 columns]
Rows where 'deed_volume' has fake nulls:
        deed_volume
0               NaN
1               NaN
14              NaN
15              NaN
23              NaN
...             ...
3014831         NaN
3014836         NaN
3014838         NaN
3014852         NaN
3014853         NaN

[710186 rows x 1 columns]
Rows where 'deed_page' has fake nulls:
        deed_page
0             NaN
1             NaN
14            NaN
15            NaN
23            NaN
...           ...
3014831       NaN
3014836       NaN
3014838       NaN
3014852       NaN
3014853       NaN

[710254 rows x 1 columns]
Rows where 'owner_name' has fake nulls:
        owner_name
5693           NaN
8627           NaN
26165          NaN
29318          NaN
32568          NaN
...            ...
3001880        NaN
3005002        NaN
3010276        NaN
3010534        NaN
3012797        NaN

[641 rows x 1 columns]

NaN count per column:
acc_nu              0
geo_no              0
instrument        290
deed_volume    710186
deed_page      710254
date                0
owner_name        641
page_save           0
dtype: int64

Cleaned DataFrame:
           acc_nu       geo_no      instrument deed_volume deed_page  \
0        02097354   31280-20-8      D221362700         NaN       NaN
1        02097354   31280-20-8      D218282153         NaN       NaN
2        02097354   31280-20-8      D214122114     0000000       0.0
3        02097354   31280-20-8  00116860000180     0011686     180.0
4        02097354   31280-20-8  00116860000134     0011686     134.0
...           ...          ...             ...         ...       ...
3014858  07254253  26368C-1-49  00141080000603     14108.0     603.0
3014859  07254253  26368C-1-49  00000000000000         0.0       0.0
3014860  40228584  33901C-4-26      D203318382     17118.0     372.0
3014861  40228584  33901C-4-26  00167460000006     16746.0       6.0
3014862  40228584  33901C-4-26  00000000000000         0.0       0.0

               date                            owner_name      page_save
0        12/10/2021  ESTES JOHN DAVID;ESTES STACY LABORDE  02097354.html
1        12/28/2018           CROCKETT AMY;CROCKETT EMILY  02097354.html
2          6/6/2014                       RAMSAY THOMAS W  02097354.html
3          8/5/1994             BEAN CHERYL;BEAN JOHN III  02097354.html
4         7/11/1994          MIDLAND LAND INVESTMENTS INC  02097354.html
...             ...                                   ...            ...
3014858  11/12/1999            HOUCK E DWAIN;HOUCK K DAWN  07254253.html
3014859    1/1/1998                  D R HORTON TEXAS LTD  07254253.html
3014860   8/22/2003                         SHISLER KERRY  40228584.html
3014861   5/22/2003            GOODMAN FAMILY OF BLDRS LP  40228584.html
3014862    1/1/2003                                  IPCF  40228584.html

[3014863 rows x 8 columns]

In [5]:
import re
for col in df.select_dtypes(include=['object']).columns:
    df[col] = df[col].apply(
        lambda x: re.sub(r'\s+', ' ', x).strip() if isinstance(x, str) else x
    )

In [6]:
df

,acc_nu,geo_no,instrument,deed_volume,deed_page,date,owner_name,page_save
0,02097354,31280-20-8,D221362700,NaN,NaN,12/10/2021,ESTES JOHN DAVID;ESTES STACY LABORDE,02097354.html
1,02097354,31280-20-8,D218282153,NaN,NaN,12/28/2018,CROCKETT AMY;CROCKETT EMILY,02097354.html
2,02097354,31280-20-8,D214122114,0000000,0.0,6/6/2014,RAMSAY THOMAS W,02097354.html
3,02097354,31280-20-8,00116860000180,0011686,180.0,8/5/1994,BEAN CHERYL;BEAN JOHN III,02097354.html
4,02097354,31280-20-8,00116860000134,0011686,134.0,7/11/1994,MIDLAND LAND INVESTMENTS INC,02097354.html
...,...,...,...,...,...,...,...,...
3014858,07254253,26368C-1-49,00141080000603,14108.0,603.0,11/12/1999,HOUCK E DWAIN;HOUCK K DAWN,07254253.html
3014859,07254253,26368C-1-49,00000000000000,0.0,0.0,1/1/1998,D R HORTON TEXAS LTD,07254253.html
3014860,40228584,33901C-4-26,D203318382,17118.0,372.0,8/22/2003,SHISLER KERRY,40228584.html
3014861,40228584,33901C-4-26,00167460000006,16746.0,6.0,5/22/2003,GOODMAN FAMILY OF BLDRS LP,40228584.html
3014862,40228584,33901C-4-26,00000000000000,0.0,0.0,1/1/2003,IPCF,40228584.html

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3014863 entries, 0 to 3014862
Data columns (total 8 columns):
 #   Column       Dtype
---  ------       -----
 0   acc_nu       object
 1   geo_no       object
 2   instrument   object
 3   deed_volume  object
 4   deed_page    object
 5   date         object
 6   owner_name   object
 7   page_save    object
dtypes: object(8)
memory usage: 184.0+ MB

In [8]:
df[df['acc_nu'].str.len()==8]

,acc_nu,geo_no,instrument,deed_volume,deed_page,date,owner_name,page_save
0,02097354,31280-20-8,D221362700,NaN,NaN,12/10/2021,ESTES JOHN DAVID;ESTES STACY LABORDE,02097354.html
1,02097354,31280-20-8,D218282153,NaN,NaN,12/28/2018,CROCKETT AMY;CROCKETT EMILY,02097354.html
2,02097354,31280-20-8,D214122114,0000000,0.0,6/6/2014,RAMSAY THOMAS W,02097354.html
3,02097354,31280-20-8,00116860000180,0011686,180.0,8/5/1994,BEAN CHERYL;BEAN JOHN III,02097354.html
4,02097354,31280-20-8,00116860000134,0011686,134.0,7/11/1994,MIDLAND LAND INVESTMENTS INC,02097354.html
...,...,...,...,...,...,...,...,...
3014858,07254253,26368C-1-49,00141080000603,14108.0,603.0,11/12/1999,HOUCK E DWAIN;HOUCK K DAWN,07254253.html
3014859,07254253,26368C-1-49,00000000000000,0.0,0.0,1/1/1998,D R HORTON TEXAS LTD,07254253.html
3014860,40228584,33901C-4-26,D203318382,17118.0,372.0,8/22/2003,SHISLER KERRY,40228584.html
3014861,40228584,33901C-4-26,00167460000006,16746.0,6.0,5/22/2003,GOODMAN FAMILY OF BLDRS LP,40228584.html
3014862,40228584,33901C-4-26,00000000000000,0.0,0.0,1/1/2003,IPCF,40228584.html

In [9]:
df[df['acc_nu']=='02097354']

,acc_nu,geo_no,instrument,deed_volume,deed_page,date,owner_name,page_save
0,02097354,31280-20-8,D221362700,NaN,NaN,12/10/2021,ESTES JOHN DAVID;ESTES STACY LABORDE,02097354.html
1,02097354,31280-20-8,D218282153,NaN,NaN,12/28/2018,CROCKETT AMY;CROCKETT EMILY,02097354.html
2,02097354,31280-20-8,D214122114,0000000,0.0,6/6/2014,RAMSAY THOMAS W,02097354.html
3,02097354,31280-20-8,00116860000180,0011686,180.0,8/5/1994,BEAN CHERYL;BEAN JOHN III,02097354.html
4,02097354,31280-20-8,00116860000134,0011686,134.0,7/11/1994,MIDLAND LAND INVESTMENTS INC,02097354.html
5,02097354,31280-20-8,00112800000972,0011280,972.0,10/6/1993,BROYLES ALLEN W,02097354.html
6,02097354,31280-20-8,00111450001303,0011145,1303.0,7/6/1993,COLONIAL SAVINGS,02097354.html
7,02097354,31280-20-8,00109520000114,0010952,114.0,2/2/1993,COLONIAL SAVINGS & LOAN ASSN,02097354.html
8,02097354,31280-20-8,00087670000448,0008767,448.0,12/3/1986,YEARY ED NEWTON,02097354.html
9,02097354,31280-20-8,00000000000000,0000000,0.0,12/31/1900,YEARY ED N,02097354.html

In [10]:
df[df['instrument'].str.len()==1]

,acc_nu,geo_no,instrument,deed_volume,deed_page,date,owner_name,page_save
91584,41084179,15927-8-2,2,0000000,0000000,1/1/2006,GRAHAM RANCH PARTNERS LTD,41084179.html
99082,41730828,46455-3-23R,1,NaN,NaN,1/2/2014,HIEMENZ JEFFREY C,41730828.html
231999,41408616,44715T-168-29,D,0000000,0.0,11/18/2009,ALI RAJESH;ALI SHERRI LEE,41408616.html
236990,41307984,22726-10-1,1,NaN,NaN,10/30/2015,LENNAR HOMES OF TEXAS LAND AND CONSTRUCTION LTD,41307984.html
403687,41289013,39762-M-36,D,0.0,0.0,9/4/2013,EL-KHOURY ROLAND,41289013.html
477865,41730801,46455-3-22R,1,NaN,NaN,1/2/2014,FERGUS DANIEL F,41730801.html
739959,41730860,46455-3-27R,1,NaN,NaN,1/2/2014,LOVERIN DENNY;LOVERIN SUSAN,41730860.html
740151,41730887,46455-3-29R,1,NaN,NaN,1/2/2014,GAINES JANE A;GAINES JOSEPH III,41730887.html
853496,40623513,37880A-7-4,M,NaN,NaN,9/27/2014,SOUTH JACQUELYN L,40623513.html
894222,41717120,34911-1-3R1,2,NaN,NaN,1/2/2014,ENERVEST ENERGY INSTITUTIONAL,41717120.html
982509,41084187,15927-8-3,2,0000000,0.0,1/1/2006,GRAHAM RANCH PARTNERS LTD,41084187.html
1136262,41705505,24060-17R-18R,1,NaN,NaN,1/2/2014,FELLOWSHIP CHURCH,41705505.html
1168107,41730844,46455-3-25R,1,NaN,NaN,1/2/2014,SHAW ROBERT W IV;STITES KEITH,41730844.html
1189481,06103650,40794-6-3,1,0010201,1230.0,3/14/1991,STRELKO PETER T EST,06103650.html
1200976,05790824,17659-1-11,D,0000000,0.0,5/17/2013,JLPREI LLC,05790824.html
1273149,41730836,46455-3-24R,1,NaN,NaN,1/2/2014,ANDREWS KEN E EST;ANDREWS SUE,41730836.html
1308580,03492249,45955-2-5,D,0.0,0.0,9/29/2008,NYKAZA JOHN J ETAL;NYKAZA MARILYN,03492249.html
1627221,41717163,46455-3-6R,2,NaN,NaN,1/2/2014,FIKES JACK;FIKES MARTHA,41717163.html
1652678,40657485,24368-20-3,D,0000000,0.0,5/18/2006,NGUYEN TUAN ANH,40657485.html
1685787,42174404,23245-27-17R,2,NaN,NaN,9/3/2016,TROTTER ELLIOTT R;TROTTER VICKY J,42174404.html
1829151,05479371,17983-9-8,D,0000000,0000000,5/17/2013,HALE SHAWN;HALE MARIA,05479371.html
1874319,41084160,15927-8-1,2,0.0,0.0,1/1/2006,GRAHAM RANCH PARTNERS LTD,41084160.html
1874466,41084195,15927-8-4,2,0.0,0.0,1/1/2006,GRAHAM RANCH PARTNERS LTD,41084195.html
1878005,41717171,46455-3-12R,2,NaN,NaN,1/2/2014,WEISER JOHN M;WEISER TERRI L,41717171.html
2128302,41086066,15927-7-8,2,0000000,0.0,1/1/2006,GRAHAM RANCH PARTNERS LTD,41086066.html
2255908,00190772,2320-H-17,D,NaN,NaN,8/11/2011,MANDELL THOMAS R,00190772.html
2318771,07917023,14133E-18-20,2,0016726,0000261,5/15/2003,WALLACE JOHN A,07917023.html
2336917,05930081,39955-1-10,1,0009372,0002052,9/1/1988,VINCENT DENISE A EST;VINCENT JOHN E,05930081.html
2406217,06943195,30588-10-12,2,13821.0,546.0,4/5/1999,JAW HOMES INC,06943195.html
2620102,41730852,46455-3-26R,1,NaN,NaN,1/2/2014,LONGO-KAZANOVA LINDA;LONGO-KAZANOVA W,41730852.html
2704637,07917201,14133E-19-6,2,16084.0,249.0,10/4/2002,JAW HOMES INC,07917201.html
2735708,05065011,23785-1-16,D,9812.0,1224.0,5/3/1989,ARNOLD GARY B;ARNOLD VICKI L,05065011.html
2746487,41705483,24060-16-16R,1,NaN,NaN,1/2/2014,FELLOWSHIP CHURCH,41705483.html
2793983,41084276,15927-8-11,2,0.0,0.0,1/1/2006,GRAHAM RANCH PARTNERS LTD,41084276.html
2869377,41730879,46455-3-28R,1,NaN,NaN,1/2/2014,TIERNEY DAVID;TIERNEY JULIANNA,41730879.html
2942850,05740649,30257-6-7,D,0.0,0.0,7/26/2011,EVERGREEN ELITE REALTY LLC,05740649.html

## Replacing the 'M' and 'D' from column 'instrument'

In [11]:
df['instrument'] = df['instrument'].replace(['M','D'],np.nan)
df['instrument']

0              D221362700
1              D218282153
2              D214122114
3          00116860000180
4          00116860000134
                ...
3014858    00141080000603
3014859    00000000000000
3014860        D203318382
3014861    00167460000006
3014862    00000000000000
Name: instrument, Length: 3014863, dtype: object

In [12]:
for col in df.columns:
    print(f"\n--- {col} ---")
    print(df[col].value_counts(dropna=True))

--- acc_nu ---
acc_nu
06060587    29
00789623    29
00795690    28
03216608    28
01060899    28
            ..
41159969     1
42630329     1
06309712     1
03713016     1
03723674     1
Name: count, Length: 607620, dtype: int64

--- geo_no ---
geo_no
7848C-09          30
18135-2-1A        29
10820-3-22        29
44120-23-3        28
10840-25-1        28
                  ..
47475-6-1          1
43796T-B-1X-09     1
46673A-3-4         1
20960-5-5          1
14218-1-41A        1
Name: count, Length: 607363, dtype: int64

--- instrument ---
instrument
00000000000000    563926
DC                  1113
00144030000441      1003
00153420000166       971
00091160000932       666
                   ...
00140280000389         1
D208176473             1
00141080000603         1
D203318382             1
00167460000006         1
Name: count, Length: 2111327, dtype: int64

--- deed_volume ---
deed_volume
0000000    924052
0.0        300258
0014403       921
0015342       813
0009116       633
            ...
6666.0          1
97424.0         1
010550          1
0001771         1
0096285         1
Name: count, Length: 31478, dtype: int64

--- deed_page ---
deed_page
0.0        1016894
0000000     208511
166.0         1741
1.0           1581
441.0         1400
            ...
6752.0           1
6877.0           1
76140.0          1
3840.0           1
5215.0           1
Name: count, Length: 5537, dtype: int64

--- date ---
date
12/31/1900    274022
1/1/2005       19752
1/1/2004       17230
1/1/2003       15806
1/1/2006       14918
               ...
11/5/1973          1
1/10/1919          1
10/7/1900          1
12/1/1977          1
9/9/1970           1
Name: count, Length: 23009, dtype: int64

--- owner_name ---
owner_name
SECRETARY OF HUD                        23447
SEC OF HUD                               9312
CHOICE HOMES INC                         8548
DR HORTON - TEXAS LTD                    8130
FIRST TEXAS HOMES INC                    6633
                                        ...
SARDAS CLAUDIA M;SARDAS PRIMITIVO           1
JONES-FOSTER CYRO                           1
YEARY ED NEWTON                             1
BEAN CHERYL;BEAN JOHN III                   1
ESTES JOHN DAVID;ESTES STACY LABORDE        1
Name: count, Length: 1732327, dtype: int64

--- page_save ---
page_save
06060587.html    29
00789623.html    29
00795690.html    28
03216608.html    28
01060899.html    28
                 ..
41159969.html     1
42630329.html     1
06309712.html     1
03713016.html     1
03723674.html     1
Name: count, Length: 607620, dtype: int64

In [13]:
df[df['date']=='5/8/7791']

,acc_nu,geo_no,instrument,deed_volume,deed_page,date,owner_name,page_save
43961,05087791,30593-W-21,D215063659,NaN,NaN,5/8/7791,OSF IV LOC BORROWER LLC,05087791.html

## Found invalid date so kept as it is only chnage the proper date to date formatting

In [14]:
parsed = pd.to_datetime(df['date'], errors='coerce')
df['date'] = parsed.dt.strftime('%Y-%m-%d').where(parsed.notna(), df['date'])
df['date']

0          2021-12-10
1          2018-12-28
2          2014-06-06
3          1994-08-05
4          1994-07-11
              ...
3014858    1999-11-12
3014859    1998-01-01
3014860    2003-08-22
3014861    2003-05-22
3014862    2003-01-01
Name: date, Length: 3014863, dtype: object

In [15]:
df[df['date']=='5/8/7791']

,acc_nu,geo_no,instrument,deed_volume,deed_page,date,owner_name,page_save
43961,05087791,30593-W-21,D215063659,NaN,NaN,5/8/7791,OSF IV LOC BORROWER LLC,05087791.html

In [16]:
df['date'].value_counts()

date
1900-12-31    274022
2005-01-01     19752
2004-01-01     17230
2003-01-01     15806
2006-01-01     14918
               ...
1973-11-05         1
1919-01-10         1
1900-10-07         1
1977-12-01         1
1970-09-09         1
Name: count, Length: 23009, dtype: int64

In [17]:
df[df['deed_volume'].str.len()==1]

,acc_nu,geo_no,instrument,deed_volume,deed_page,date,owner_name,page_save
5091,02703459,37860-49-21,CW D224152430,0,0.0,2000-05-25,KEITH STEPHEN H,02703459.html
13523,02161591,31808-69-13,CWD223223687,0,0.0,2002-09-19,DONALD C LITTLE FAMILY LP,02161591.html
14915,01643134,25080-2-16-11,D217053879-CWD,0,0.0,2014-06-28,RAMIREZ SANTIAGO R ETAL,01643134.html
15831,02237237,32750-40-1B,D218022158-CWD,0,0.0,2012-04-11,LTR INVESTMENTS LLC,02237237.html
17013,03044890,40880-2-7,D217192649-CWD,0,0.0,2009-12-04,WHITLEY DARRELL JR;WHITLEY DARRELL SR,03044890.html
...,...,...,...,...,...,...,...,...
2996301,07374844,26236-E-5,D225100555,`,NaN,2025-05-23,BARKARE BOLAJOKO O;BARKARE OLUGBENGA,07374844.html
3004861,00120804,1650-2-20,D212007228,0,0.0,2012-01-09,BARRERA JUAN G ARELLANO,00120804.html
3009223,02369990,34190-34-11,D217175072,0,0.0,2008-12-28,DAVIDSON ANDREW B;DAVIDSON LINDSEY,02369990.html
3010534,03040216,40860-T-33,D205369846,0,0.0,2005-11-22,NaN,03040216.html
3012831,02067706,31030-27-1,02-1735-2,0,0.0,2002-05-09,SEVAR PHILIP W TYLER;SEVAR SUSAN K,02067706.html

In [18]:
df[df['deed_page'].str.len()==1]

,acc_nu,geo_no,instrument,deed_volume,deed_page,date,owner_name,page_save
69998,02240483,32750-60-9,D211083779,0,0,2011-04-11,REED LEONARD B,02240483.html
78180,40585727,25413-3-19,D218108409-CWD,0,0,2006-04-04,ARCHAMBEAU MELISSA D,40585727.html
81983,02432226,34410-24-31,D220200611-CWD,0,0,2007-02-01,MITCHELL DONALD B,02432226.html
86315,01921614,30000-161-10,D196159536,0,0,1996-08-08,REYES ABIGAIL EST,01921614.html
91766,03482286,46280-6-13,D219180129,0,0,2010-02-02,PERL TRUST,03482286.html
...,...,...,...,...,...,...,...,...
2823438,41539591,21025A-2-9R,D222232017,0,0,2011-10-26,POULSON KYLE;POULSON ERIN,41539591.html
2824078,07182287,10884-4-61,D217173545-CWD,0,0,2004-07-21,SABOLCHICK STEPHEN GEORGE,07182287.html
2834794,07018797,34985-26-11,D221077210,0,0,2014-04-09,YOUNG BETTY L;YOUNG WILLIAM C,07018797.html
2849235,07560222,7088H-A-29,D219031481,NaN,`,2019-02-15,ADAMCIK BRIAN;ADAMCIK KALLIE,07560222.html
2882462,06551718,42163C-7-8,D220306495CORR,0,0,2007-03-15,LOGAN LINDA;LOGAN SUMPTER,06551718.html

In [19]:
df[df['owner_name'].str.len()==1]

,acc_nu,geo_no,instrument,deed_volume,deed_page,date,owner_name,page_save
2481394,00019321,310-9-6-10,00000000000000,0000000,0.0,1900-12-30,S,00019321.html

## Replacing the 'S' with null from column 'owner_name'

In [20]:
df['owner_name'] = df['owner_name'].replace('S',np.nan)
df['owner_name']

0          ESTES JOHN DAVID;ESTES STACY LABORDE
1                   CROCKETT AMY;CROCKETT EMILY
2                               RAMSAY THOMAS W
3                     BEAN CHERYL;BEAN JOHN III
4                  MIDLAND LAND INVESTMENTS INC
                           ...
3014858              HOUCK E DWAIN;HOUCK K DAWN
3014859                    D R HORTON TEXAS LTD
3014860                           SHISLER KERRY
3014861              GOODMAN FAMILY OF BLDRS LP
3014862                                    IPCF
Name: owner_name, Length: 3014863, dtype: object

In [21]:
df[df['owner_name'].str.len()==1]

Empty DataFrame
Columns: [acc_nu, geo_no, instrument, deed_volume, deed_page, date, owner_name, page_save]
Index: []

In [22]:
df

,acc_nu,geo_no,instrument,deed_volume,deed_page,date,owner_name,page_save
0,02097354,31280-20-8,D221362700,NaN,NaN,2021-12-10,ESTES JOHN DAVID;ESTES STACY LABORDE,02097354.html
1,02097354,31280-20-8,D218282153,NaN,NaN,2018-12-28,CROCKETT AMY;CROCKETT EMILY,02097354.html
2,02097354,31280-20-8,D214122114,0000000,0.0,2014-06-06,RAMSAY THOMAS W,02097354.html
3,02097354,31280-20-8,00116860000180,0011686,180.0,1994-08-05,BEAN CHERYL;BEAN JOHN III,02097354.html
4,02097354,31280-20-8,00116860000134,0011686,134.0,1994-07-11,MIDLAND LAND INVESTMENTS INC,02097354.html
...,...,...,...,...,...,...,...,...
3014858,07254253,26368C-1-49,00141080000603,14108.0,603.0,1999-11-12,HOUCK E DWAIN;HOUCK K DAWN,07254253.html
3014859,07254253,26368C-1-49,00000000000000,0.0,0.0,1998-01-01,D R HORTON TEXAS LTD,07254253.html
3014860,40228584,33901C-4-26,D203318382,17118.0,372.0,2003-08-22,SHISLER KERRY,40228584.html
3014861,40228584,33901C-4-26,00167460000006,16746.0,6.0,2003-05-22,GOODMAN FAMILY OF BLDRS LP,40228584.html
3014862,40228584,33901C-4-26,00000000000000,0.0,0.0,2003-01-01,IPCF,40228584.html

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3014863 entries, 0 to 3014862
Data columns (total 8 columns):
 #   Column       Dtype
---  ------       -----
 0   acc_nu       object
 1   geo_no       object
 2   instrument   object
 3   deed_volume  object
 4   deed_page    object
 5   date         object
 6   owner_name   object
 7   page_save    object
dtypes: object(8)
memory usage: 184.0+ MB

In [24]:
df.duplicated().sum()

np.int64(679)

## Drop 1 duplicated records

In [25]:
df = df.drop_duplicates(keep='first')

In [26]:
df.duplicated().sum()

np.int64(0)

In [27]:
df.columns

Index(['acc_nu', 'geo_no', 'instrument', 'deed_volume', 'deed_page', 'date',
       'owner_name', 'page_save'],
      dtype='object')

In [28]:
cols = df.columns.difference(['acc_nu', 'page_save'])
 
mask = df[cols].isna().all(axis=1)
df[mask]

Empty DataFrame
Columns: [acc_nu, geo_no, instrument, deed_volume, deed_page, date, owner_name, page_save]
Index: []

In [29]:
df

,acc_nu,geo_no,instrument,deed_volume,deed_page,date,owner_name,page_save
0,02097354,31280-20-8,D221362700,NaN,NaN,2021-12-10,ESTES JOHN DAVID;ESTES STACY LABORDE,02097354.html
1,02097354,31280-20-8,D218282153,NaN,NaN,2018-12-28,CROCKETT AMY;CROCKETT EMILY,02097354.html
2,02097354,31280-20-8,D214122114,0000000,0.0,2014-06-06,RAMSAY THOMAS W,02097354.html
3,02097354,31280-20-8,00116860000180,0011686,180.0,1994-08-05,BEAN CHERYL;BEAN JOHN III,02097354.html
4,02097354,31280-20-8,00116860000134,0011686,134.0,1994-07-11,MIDLAND LAND INVESTMENTS INC,02097354.html
...,...,...,...,...,...,...,...,...
3014858,07254253,26368C-1-49,00141080000603,14108.0,603.0,1999-11-12,HOUCK E DWAIN;HOUCK K DAWN,07254253.html
3014859,07254253,26368C-1-49,00000000000000,0.0,0.0,1998-01-01,D R HORTON TEXAS LTD,07254253.html
3014860,40228584,33901C-4-26,D203318382,17118.0,372.0,2003-08-22,SHISLER KERRY,40228584.html
3014861,40228584,33901C-4-26,00167460000006,16746.0,6.0,2003-05-22,GOODMAN FAMILY OF BLDRS LP,40228584.html
3014862,40228584,33901C-4-26,00000000000000,0.0,0.0,2003-01-01,IPCF,40228584.html

In [30]:
checks = {
    "Numeric 0": 0,
    "String '0'": '0',
    "Hyphen '-'": '-',
    "Dot '.'": '.',
    "Comma ','": ',',
    "Backtick '`'": '`'
}

for label, val in checks.items():
    print(f"\n=== {label} ===")
    result = (df == val).sum().loc[lambda x: x > 0]
    print(result if not result.empty else "No matches found")

=== Numeric 0 ===
deed_volume     300232
deed_page      1016827
dtype: int64

=== String '0' ===
deed_volume    543
deed_page      110
dtype: int64

=== Hyphen '-' ===
No matches found

=== Dot '.' ===
No matches found

=== Comma ',' ===
No matches found

=== Backtick '`' ===
deed_volume    31
deed_page       4
dtype: int64

In [31]:
df.columns

Index(['acc_nu', 'geo_no', 'instrument', 'deed_volume', 'deed_page', 'date',
       'owner_name', 'page_save'],
      dtype='object')

## Replacing the '0' and '`' with null from column  'deed_volume', 'deed_page'

In [32]:
col = [ 'deed_volume', 'deed_page',]
df[col] = df[col].replace(['`',0,'0','0000000'], np.nan)
df[col]

C:\Users\khushi.limbachiya\AppData\Local\Temp\ipykernel_12932\2345814719.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = df[col].replace(['`',0,'0','0000000'], np.nan)

        deed_volume deed_page
0               NaN       NaN
1               NaN       NaN
2               NaN       NaN
3           0011686     180.0
4           0011686     134.0
...             ...       ...
3014858     14108.0     603.0
3014859         NaN       NaN
3014860     17118.0     372.0
3014861     16746.0       6.0
3014862         NaN       NaN

[3014184 rows x 2 columns]

In [33]:
checks = {
    "Numeric 0": 0,
    "String '0'": '0',
    "Hyphen '-'": '-',
    "Dot '.'": '.',
    "Comma ','": ',',
    "Backtick '`'": '`'
}

for label, val in checks.items():
    print(f"\n=== {label} ===")
    result = (df == val).sum().loc[lambda x: x > 0]
    print(result if not result.empty else "No matches found")

=== Numeric 0 ===
No matches found

=== String '0' ===
No matches found

=== Hyphen '-' ===
No matches found

=== Dot '.' ===
No matches found

=== Comma ',' ===
No matches found

=== Backtick '`' ===
No matches found

In [34]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3014184 entries, 0 to 3014862
Data columns (total 8 columns):
 #   Column       Dtype
---  ------       -----
 0   acc_nu       object
 1   geo_no       object
 2   instrument   object
 3   deed_volume  object
 4   deed_page    object
 5   date         object
 6   owner_name   object
 7   page_save    object
dtypes: object(8)
memory usage: 207.0+ MB

In [35]:
df.columns

Index(['acc_nu', 'geo_no', 'instrument', 'deed_volume', 'deed_page', 'date',
       'owner_name', 'page_save'],
      dtype='object')

In [36]:
df = df.rename(columns={'acc_nu':'account_no'})

In [37]:
df.columns

Index(['account_no', 'geo_no', 'instrument', 'deed_volume', 'deed_page',
       'date', 'owner_name', 'page_save'],
      dtype='object')

In [38]:
df

,account_no,geo_no,instrument,deed_volume,deed_page,date,owner_name,page_save
0,02097354,31280-20-8,D221362700,NaN,NaN,2021-12-10,ESTES JOHN DAVID;ESTES STACY LABORDE,02097354.html
1,02097354,31280-20-8,D218282153,NaN,NaN,2018-12-28,CROCKETT AMY;CROCKETT EMILY,02097354.html
2,02097354,31280-20-8,D214122114,NaN,NaN,2014-06-06,RAMSAY THOMAS W,02097354.html
3,02097354,31280-20-8,00116860000180,0011686,180.0,1994-08-05,BEAN CHERYL;BEAN JOHN III,02097354.html
4,02097354,31280-20-8,00116860000134,0011686,134.0,1994-07-11,MIDLAND LAND INVESTMENTS INC,02097354.html
...,...,...,...,...,...,...,...,...
3014858,07254253,26368C-1-49,00141080000603,14108.0,603.0,1999-11-12,HOUCK E DWAIN;HOUCK K DAWN,07254253.html
3014859,07254253,26368C-1-49,00000000000000,NaN,NaN,1998-01-01,D R HORTON TEXAS LTD,07254253.html
3014860,40228584,33901C-4-26,D203318382,17118.0,372.0,2003-08-22,SHISLER KERRY,40228584.html
3014861,40228584,33901C-4-26,00167460000006,16746.0,6.0,2003-05-22,GOODMAN FAMILY OF BLDRS LP,40228584.html
3014862,40228584,33901C-4-26,00000000000000,NaN,NaN,2003-01-01,IPCF,40228584.html

## Placing the file

In [39]:
df.to_csv(r'D:\Khushi\Cleansing_Data\us\texas\tarrant\transaction_log\Cleaned_Data\us_tx_48439_data_prop_sales_silver_20260218.csv',index=False)